# Generated by Django 2.0.7 on 2018-07-30 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signupAndLogin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormNew',
            new_name='Users',
        ),
    ]
