# Generated by Django 2.0.7 on 2018-07-30 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signupAndLogin', '0002_auto_20180730_1605'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
