# Generated by Django 2.0.7 on 2018-07-31 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signupAndLogin', '0003_auto_20180730_1616'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
