# Generated by Django 2.0.7 on 2018-08-06 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signupAndLogin', '0008_items_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='CustomUserModel',
        ),
        migrations.AlterField(
            model_name='items',
            name='Itemuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CustomUserModel',
        ),
    ]
