# Generated by Django 2.0.7 on 2018-08-06 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signupAndLogin', '0010_auto_20180806_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractusermodel',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='abstractusermodel',
            name='item',
        ),
        migrations.RemoveField(
            model_name='abstractusermodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='abstractusermodel',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='AbstractUserModel',
        ),
    ]
